version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports: 
      - 1972
      - 52773:52773
      - 53773
      - 9980:9980
    volumes:
      - ./:/irisdev/app
      - ./json:/opt/user/json